name: 'Get & Cache Dependencies'
description: 'Get code and cache dependencies for Node.js projects'
inputs:
  caching:
    description: 'Enable caching of dependencies'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Indicates if the cache was hit'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.used-cache != 'true' || ${{ inputs.caching != 'true' }}
      run: |
        npm ci
        echo "Cache hit: ::set-output name=cache::'${{ inputs.caching }}'"
      shell: bash